apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.postgres.port }}
      protocol: {{ .Values.db.service.protocol }}
  selector:
    airbyte: {{ .Values.db.label }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.metadataName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: {{ .Values.db.label }}
  template:
    metadata:
      labels:
        airbyte: {{ .Values.db.label }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.image.db }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.configName }}
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.configName }}
                  key: DATABASE_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.configName }}
                  key: DATABASE_USER
          ports:
            - containerPort: {{ .Values.db.postgres.port }}
          volumeMounts:
            - name: {{ .Values.persistence.db.volumeName }}
              mountPath: {{ .Values.persistence.db.mountPath }}
            - name: {{ .Values.configmap.configName }}
              mountPath:  {{ .Values.configmap.mountPath }}
              readOnly: true
      volumes:
        - name: {{ .Values.persistence.db.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.db.volumeName }}
        - name: {{ .Values.configmap.configName }}
          configMap:
            name: {{ .Values.configmap.configName }}