apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.rbac.name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["{{ .Values.serviceAccount.rbac.rules.apiGroups }}"]
    resources: {{ .Values.serviceAccount.rbac.rules.resources }}
    verbs: {{ .Values.serviceAccount.rbac.rules.verbs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.rbac.roleBinding }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ .Values.serviceAccount.rbac.roleRef }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
