apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.temporal.service.name }}
spec:
  type: {{ .Values.temporal.service.type }}
  ports:
    - port: {{ .Values.temporal.service.port }}
      protocol: {{ .Values.temporal.service.protocol }}
  selector:
    airbyte: {{ .Values.temporal.label }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.temporal.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: {{ .Values.temporal.label }}
  template:
    metadata:
      labels:
        airbyte: {{ .Values.temporal.label }}
    spec:
      containers:
        - name: {{ .Values.temporal.name }}
          image: "{{ .Values.image.temporal }}:{{ .Values.image.temporalVersion | default .Chart.AppVersion }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.configName }}
                  key: DATABASE_USER
            - name: POSTGRES_PWD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.configName }}
                  key: DATABASE_PASSWORD
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "{{ .Values.temporal.file.configPath }}{{ .Values.temporal.file.name }}"
            - name: DB
              value: {{ .Values.db.postgres.dbTemporal }}
            - name: DB_PORT
              value: "{{ .Values.db.postgres.port }}"
            - name: POSTGRES_SEEDS
              value: {{ .Values.db.service.name }}
          ports:
            - containerPort: {{ .Values.temporal.service.port }}
          volumeMounts:
            - name: {{ .Values.temporal.configmap.name }}
              mountPath: {{ .Values.temporal.configmap.mountPath }}
            - name: {{ .Values.configmap.configName }}
              mountPath:  {{ .Values.configmap.mountPath }}
              readOnly: true
      volumes:
        - name: {{ .Values.temporal.configmap.name }}
          configMap:
            name: {{ .Values.temporal.configmap.name }}
            items:
              - key: {{ .Values.temporal.file.name }}
                path: {{ .Values.temporal.file.name }}
        - name: {{ .Values.configmap.configName }}
          configMap:
            name: {{ .Values.configmap.configName }}